---
util_packages:
  - name: fakeroot
  - name: keepassx
  - name: pv
  - name: pwgen
  - name: silversearcher-ag
  - name: strace
  - name: suckless-tools
  - name: sysstat
  - name: unp
  - name: unzip
  - name: wajig
