- name: add users
  sudo: yes
  user:
    name: "meka"
    shell: "/usr/bin/fish"
    groups: "audio,video,sudo"
    append: yes

- name: configure cron for meka
  sudo: yes
  sudo_user: meka
  cron:
    name: run ~/bin stuf
    state: present
    job: ~/bin/cron.sh
    minute: "*"

- name: install vex
  sudo: yes
  sudo_user: meka
  pip:
    name: vex
    extra_args: "--user"
    state: present

- name: install user pip packages
  with_items: user_pip_packages
  sudo: yes
  sudo_user: meka
  pip:
    name: "{{ item.name }}"
    virtualenv: "~/.virtualenvs/v"
    state: present

- name: download rofi
  sudo: yes
  sudo_user: meka
  git:
    repo: https://github.com/DaveDavenport/rofi
    dest: ~/rofi
    accept_hostkey: yes
    depth: 1

- name: autoreconfigure rofi
  sudo: yes
  sudo_user: meka
  command: autoreconf -i
  args:
    chdir: ~/rofi
    creates: ~/rofi/configure

- name: configure rofi
  sudo: yes
  sudo_user: meka
  command: ./configure
  args:
    chdir: ~/rofi
    creates: ~/rofi/rofi

- name: make rofi
  sudo: yes
  sudo_user: meka
  command: make
  args:
    chdir: ~/rofi
    creates: ~/rofi/rofi

- name: make install rofi
  sudo: yes
  command: make install
  args:
    chdir: ~meka/rofi
    creates: /usr/local/bin/rofi

- name: ensure ~/Files exists
  sudo: yes
  sudo_user: meka
  file:
    path: ~/Files
    state: directory

- name: ensure ~/Files/repos exists
  sudo: yes
  sudo_user: meka
  file:
    path: ~/Files/repos
    state: directory

- name: clone dotfiles
  sudo: yes
  sudo_user: meka
  command: git clone https://github.com/mekanix/dotfiles.git
  args:
    chdir: ~/Files/repos
    creates: ~/Files/repos/dotfiles

- name: alter .gitmodules
  sudo: yes
  sudo_user: meka
  command: sed -i 's;url = git@github.com:;url = https://github.com/;g' ~/Files/repos/dotfiles/.gitmodules
  args:
    creates: ~/Files/repos/dotfiles/vim/bin/init.sh

- name: get dotfiles submodules
  sudo: yes
  sudo_user: meka
  command: git submodule update --init
  args:
    chdir: ~/Files/repos/dotfiles
    creates: ~/Files/repos/dotfiles/vim/bin/init.sh

- name: init configuration of programs
  sudo: yes
  sudo_user: meka
  command: ~/Files/repos/dotfiles/init.sh
  args:
    creates: ~/.vim

- name: configure git
  sudo: yes
  sudo_user: meka
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: install gem packages
  with_items: user_gem_packages
  gem:
    name: "{{ item.name }}"
    state: present

- name: create Mail directory
  sudo: yes
  file:
    path: ~meka/Mail
    owner: meka
    group: meka
    state: directory

- name: configure vimperator
  sudo: yes
  template:
    src: vimperatorrc.j2
    dest: ~meka/.vimperatorrc
    owner: meka
    group: meka
