---
web_packages:
  - name: chromium
  - name: elinks
  - name: flashplugin-nonfree
  - name: iceweasel
  - name: pepperflashplugin-nonfree
  - name: rtorrent
  - name: xul-ext-adblock-plus

web_chromium_configs:
  - name: incognito
  - name: tor
